version: '3.8'

services:
  app:
    build: .
    restart: always  # 인스턴스 재시작 시 자동 시작
    ports:
      - "80:5000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=dbjungle
      - CLEAR_DB=${CLEAR_DB:-false}
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    restart: always  # 인스턴스 재시작 시 자동 시작
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
